apiVersion: v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: skattesatser
  name: skattesatser
spec:
  to:
    kind: Service
    name: skattesatser
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
